### PR TITLE
onion integration

### PR DESCRIPTION
**Pull request by ricott1**
I extended the module to encode and decode .onion (tor) addresses. I'm planning to use this to extend the ens-app repo.

### CODE REVIEW

**Comment by ricott1** [comment]
This pull depends on another [pull request for js-multiaddr](https://github.com/multiformats/js-multiaddr/pull/89). [edit] That pull has been merged

**Comment by ricott1** [comment]
Can I get some feedback on this?

**Comment by Arachnid** [comment]
@pldespaigne Can you please take a look at this? We'd like to add support to the ENS manager, but we can't until this is merged.

**Comment by pldespaigne** [comment]
I will look at it ! @ricott1 no offense, but this PR doesn't look clean, do you think a general encoding function will do the job (see #17 ) ?

**Comment by ricott1** [comment]
Absolutely, I'm by no mean an expert developer, I just needed a way to encode onion addresses for the ens-app, but a general encoding would definitely be the way to go.

**Comment by ricott1** [comment]
Hi @pldespaigne , are you working on the general encoding by any chance?

**Comment by pldespaigne** [comment]
Hi, I don't have so much time currently, but it will be done before Sunday evening !

**Comment by pldespaigne** [comment]
Hi @ricott1 just merge #28 and publish it to npm as v2.4.1, you should now be able to do `contentHash.encode('onion', onionAddress);` (onion3 is also supported), I will update the readme later today. Please tell me if it is ok for you so I can close this PR

**Comment by ricott1** [comment]
Thanks!

**Pull request closed without merging**
